import React from 'react';
import { Feature } from '../../components';
import './features.css';

const featuresData = [
  {
    title: 'Language translation',
    text: 'GPT-3 is capable of translating to and from a variety of languages, knows billions of words, and is even capable of coding! Because of all the data GPT-3 has at hand, it requires no further training to fulfil language tasks.'
  },
  {
    title: 'Named-entity recognition',
    text: 'The main purposed of NER is information extraction. It is used to summarize a piece of text to understand the subject, theme, or other important pieces of information.'
  },
  {
    title: 'Text generation',
    text: 'The quality of the text generated by GPT-3 is so high that it can be difficult to determine whether or not it was written by a human, which has both benefits and risks.'
  },
  {
    title: 'Question answering',
    text: 'Without fine tuning, GPT-3 can perform the task of search and answering questions with high accuracy. This will revolutionize the field of technical/customer support.'
  }
]

const Features = () => {
  return (
    <div className='gpt3__features section__padding' id='features'>
      <div className='gpt3__features-heading'>
        <h1 className='gradient__text'>The Future is Now and You Just Need To Realize It. Step into Future Today & Make it Happen.</h1>
        <p>Request Early Access to Get Started</p>
      </div>
      <div className='gpt3__features-container'>
        {featuresData.map((item, index) => (
          <Feature title={item.title} text={item.text} key={item.title + index} />
        ))}
      </div>
    </div>
  )
}

export default Features;